/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controladores.ControladorTablaProveedor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexis
 */
public class EliminarProveedorLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarProveedorLista
     */
    ControladorTablaProveedor controller = new ControladorTablaProveedor();
    public EliminarProveedorLista() throws SQLException, ClassNotFoundException {
        initComponents();
        controller.mostrar(tblEliminarProveedor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEliminarProveedor = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblEliminarProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEliminarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEliminarProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEliminarProveedor);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Debe ingresar la id del proveedor para buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            controller.mostrardatos(txtId.getText(), tblEliminarProveedor);
        } catch (SQLException ex) {
            Logger.getLogger(EliminarProveedorLista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EliminarProveedorLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblEliminarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEliminarProveedorMouseClicked
        EliminarProveedor ventanaEliminarProveedor = new EliminarProveedor();
        MenuPrincipal.jdpEscritorio.add(ventanaEliminarProveedor);
        ventanaEliminarProveedor.show();
        this.setVisible(false);
        int cor =tblEliminarProveedor.getSelectedRow();
        ventanaEliminarProveedor.txtId.setText(tblEliminarProveedor.getValueAt(cor, 0).toString());
        ventanaEliminarProveedor.txtRut.setText(tblEliminarProveedor.getValueAt(cor, 1).toString());
        ventanaEliminarProveedor.txtDv.setText(tblEliminarProveedor.getValueAt(cor, 2).toString());
        ventanaEliminarProveedor.txtNombre.setText(tblEliminarProveedor.getValueAt(cor, 3).toString());
        ventanaEliminarProveedor.txtDireccion.setText(tblEliminarProveedor.getValueAt(cor, 4).toString());
        ventanaEliminarProveedor.txtContacto.setText(tblEliminarProveedor.getValueAt(cor, 5).toString());
        
        
    }//GEN-LAST:event_tblEliminarProveedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEliminarProveedor;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
