/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.ConexionBD;
import controladores.CargaComboBox;
import controladores.ControladorTablaUsuario;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis
 */
public class EliminarUsuarioLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarUsuarioLista
     */
    ControladorTablaUsuario  controller = new ControladorTablaUsuario();
    
    public EliminarUsuarioLista()throws SQLException, ClassNotFoundException {
        initComponents();
        controller.mostrar(tblUsuarios);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtRun = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            controller.mostrardatos(txtRun.getText(), tblUsuarios);
        } catch (SQLException ex) {
            Logger.getLogger(EliminarUsuarioLista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EliminarUsuarioLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
               EliminarUsuario ventanaEliminarUsuario = new EliminarUsuario();
        MenuPrincipal.jdpEscritorio.add(ventanaEliminarUsuario);
        ventanaEliminarUsuario.toFront();
        ventanaEliminarUsuario.show();
        this.setVisible(false);
        int cor = tblUsuarios.getSelectedRow();
        ventanaEliminarUsuario.txtID.setText(tblUsuarios.getValueAt(cor, 0).toString());
        ventanaEliminarUsuario.txtRun.setText(tblUsuarios.getValueAt(cor, 1).toString());
        ventanaEliminarUsuario.txtDv.setText(tblUsuarios.getValueAt(cor, 2).toString());
        ventanaEliminarUsuario.txtUsuario.setText(tblUsuarios.getValueAt(cor, 3).toString());
        ventanaEliminarUsuario.txtNombre.setText(tblUsuarios.getValueAt(cor, 4).toString());
        ventanaEliminarUsuario.txtApellidopat.setText(tblUsuarios.getValueAt(cor, 5).toString());
        ventanaEliminarUsuario.txtApellidomat.setText(tblUsuarios.getValueAt(cor, 6).toString());
        ventanaEliminarUsuario.txtCorreo.setText(tblUsuarios.getValueAt(cor, 7).toString());
        ventanaEliminarUsuario.cmbCargo.setSelectedItem(tblUsuarios.getValueAt(cor, 8).toString()); 
    }//GEN-LAST:event_tblUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtRun;
    // End of variables declaration//GEN-END:variables
}
