/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexis
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setTitle("Menú General");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        sesionCierre = new javax.swing.JMenu();
        sesionCerrarSesion = new javax.swing.JMenuItem();
        gestionUsuarios = new javax.swing.JMenu();
        gestionAgregarUsuario = new javax.swing.JMenuItem();
        gestionModificarUsuario = new javax.swing.JMenuItem();
        gestionEliminarUsuario = new javax.swing.JMenuItem();
        gestionListarUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        gestionAgregarProv = new javax.swing.JMenuItem();
        gestionModificarProv = new javax.swing.JMenuItem();
        gestionEliminarProv = new javax.swing.JMenuItem();
        gestionListarProv = new javax.swing.JMenuItem();
        gestionProductos = new javax.swing.JMenu();
        gestionAgregarProd = new javax.swing.JMenuItem();
        gestionModificarProducto = new javax.swing.JMenuItem();
        gestionEliminarProducto = new javax.swing.JMenuItem();
        gestionListarProductos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        sesionCierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/informacion1.png"))); // NOI18N
        sesionCierre.setText("Sesión");
        sesionCierre.setAlignmentX(0.0F);
        sesionCierre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sesionCierre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sesionCierre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sesionCierre.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        sesionCierre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        sesionCerrarSesion.setText("Cerrar sesión");
        sesionCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionCerrarSesionActionPerformed(evt);
            }
        });
        sesionCierre.add(sesionCerrarSesion);

        jMenuBar1.add(sesionCierre);

        gestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario1.png"))); // NOI18N
        gestionUsuarios.setText("Usuarios");
        gestionUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gestionUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestionUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionUsuarios.setMaximumSize(new java.awt.Dimension(110, 32767));
        gestionUsuarios.setPreferredSize(new java.awt.Dimension(119, 120));
        gestionUsuarios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gestionUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        gestionAgregarUsuario.setText("Agregar usuario");
        gestionAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAgregarUsuarioActionPerformed(evt);
            }
        });
        gestionUsuarios.add(gestionAgregarUsuario);

        gestionModificarUsuario.setText("Modificar usuario");
        gestionModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionModificarUsuarioActionPerformed(evt);
            }
        });
        gestionUsuarios.add(gestionModificarUsuario);

        gestionEliminarUsuario.setText("Eliminar usuario");
        gestionEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionEliminarUsuarioActionPerformed(evt);
            }
        });
        gestionUsuarios.add(gestionEliminarUsuario);

        gestionListarUsuarios.setText("Listar usuarios");
        gestionListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionListarUsuariosActionPerformed(evt);
            }
        });
        gestionUsuarios.add(gestionListarUsuarios);

        jMenuBar1.add(gestionUsuarios);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas1.png"))); // NOI18N
        jMenu3.setText("Proveedores");
        jMenu3.setActionCommand("Proveedores");
        jMenu3.setAlignmentX(0.0F);
        jMenu3.setFocusable(false);
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        gestionAgregarProv.setText("Agregar proveedor");
        gestionAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAgregarProvActionPerformed(evt);
            }
        });
        jMenu3.add(gestionAgregarProv);

        gestionModificarProv.setText("Modificar proveedor");
        gestionModificarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionModificarProvActionPerformed(evt);
            }
        });
        jMenu3.add(gestionModificarProv);

        gestionEliminarProv.setText("Eliminar proveedor");
        gestionEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionEliminarProvActionPerformed(evt);
            }
        });
        jMenu3.add(gestionEliminarProv);

        gestionListarProv.setText("Listar proveedores");
        gestionListarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionListarProvActionPerformed(evt);
            }
        });
        jMenu3.add(gestionListarProv);

        jMenuBar1.add(jMenu3);

        gestionProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alimentos1.png"))); // NOI18N
        gestionProductos.setText("Productos");
        gestionProductos.setAlignmentX(0.0F);
        gestionProductos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gestionProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestionProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gestionProductos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gestionProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        gestionAgregarProd.setText("Agregar producto");
        gestionAgregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAgregarProdActionPerformed(evt);
            }
        });
        gestionProductos.add(gestionAgregarProd);

        gestionModificarProducto.setText("Modificar producto");
        gestionModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionModificarProductoActionPerformed(evt);
            }
        });
        gestionProductos.add(gestionModificarProducto);

        gestionEliminarProducto.setText("Eliminar producto");
        gestionProductos.add(gestionEliminarProducto);

        gestionListarProductos.setText("Listar productos");
        gestionProductos.add(gestionListarProductos);

        jMenuBar1.add(gestionProductos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sesionCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sesionCerrarSesionActionPerformed

    private void gestionAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAgregarUsuarioActionPerformed
        AgregarUsuario ventanaAgregarUsuario = new AgregarUsuario();
        jdpEscritorio.add(ventanaAgregarUsuario);
        ventanaAgregarUsuario.show();
        
    }//GEN-LAST:event_gestionAgregarUsuarioActionPerformed

    private void gestionListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionListarUsuariosActionPerformed
        try {
            // TODO add your handling code here:
            ListarUsuarios ventanaListarUsuarios = new ListarUsuarios();
            jdpEscritorio.add(ventanaListarUsuarios);
            ventanaListarUsuarios.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gestionListarUsuariosActionPerformed

    private void gestionAgregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAgregarProdActionPerformed
        // TODO add your handling code here:
        AgregarProducto ventanaAgregarProducto = new AgregarProducto();
        jdpEscritorio.add(ventanaAgregarProducto);
        ventanaAgregarProducto.show();
    }//GEN-LAST:event_gestionAgregarProdActionPerformed

    private void gestionModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionModificarUsuarioActionPerformed

        ModificarUsuarioLista ventanaModificarUsuarioLista = null;
        try {
            ventanaModificarUsuarioLista = new ModificarUsuarioLista();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jdpEscritorio.add(ventanaModificarUsuarioLista);
        ventanaModificarUsuarioLista.show();
    }//GEN-LAST:event_gestionModificarUsuarioActionPerformed

    private void gestionEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionEliminarUsuarioActionPerformed
        try {
            
            EliminarUsuarioLista ventanaEliminarUsuarioLista = new EliminarUsuarioLista();
            jdpEscritorio.add(ventanaEliminarUsuarioLista);
            ventanaEliminarUsuarioLista.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestionEliminarUsuarioActionPerformed

    private void gestionAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAgregarProvActionPerformed
        // TODO add your handling code here:
        AgregarProveedor ventanaAgregarProveedor = new AgregarProveedor();
        this.jdpEscritorio.add(ventanaAgregarProveedor);
        ventanaAgregarProveedor.show();
    }//GEN-LAST:event_gestionAgregarProvActionPerformed

    private void gestionModificarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionModificarProvActionPerformed
        try {
            // TODO add your handling code here:
            ModificarProveedorLista ventanaModificarProveedorLista = new ModificarProveedorLista();
            this.jdpEscritorio.add(ventanaModificarProveedorLista);
            ventanaModificarProveedorLista.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gestionModificarProvActionPerformed

    private void gestionListarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionListarProvActionPerformed
        // TODO add your handling code here:
        
        try {
            ListarProveedores ventanaListarProveedores = new ListarProveedores();
            jdpEscritorio.add(ventanaListarProveedores);
            ventanaListarProveedores.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gestionListarProvActionPerformed

    private void gestionEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionEliminarProvActionPerformed
        try {
            // TODO add your handling code here:
            EliminarProveedorLista ventanaEliminarProveedorLista = new EliminarProveedorLista();
            jdpEscritorio.add(ventanaEliminarProveedorLista);
            ventanaEliminarProveedorLista.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestionEliminarProvActionPerformed

    private void gestionModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionModificarProductoActionPerformed
        try {
            // TODO add your handling code here:
            ModificarProductoLista ventanaModificarProductoLista = new ModificarProductoLista();
            jdpEscritorio.add(ventanaModificarProductoLista);
            ventanaModificarProductoLista.show();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestionModificarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem gestionAgregarProd;
    private javax.swing.JMenuItem gestionAgregarProv;
    private javax.swing.JMenuItem gestionAgregarUsuario;
    private javax.swing.JMenuItem gestionEliminarProducto;
    private javax.swing.JMenuItem gestionEliminarProv;
    private javax.swing.JMenuItem gestionEliminarUsuario;
    private javax.swing.JMenuItem gestionListarProductos;
    private javax.swing.JMenuItem gestionListarProv;
    private javax.swing.JMenuItem gestionListarUsuarios;
    private javax.swing.JMenuItem gestionModificarProducto;
    private javax.swing.JMenuItem gestionModificarProv;
    public static javax.swing.JMenuItem gestionModificarUsuario;
    private javax.swing.JMenu gestionProductos;
    private javax.swing.JMenu gestionUsuarios;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenuItem sesionCerrarSesion;
    private javax.swing.JMenu sesionCierre;
    // End of variables declaration//GEN-END:variables
}
